server:
  port: 8087
spring:
  redis:
    host: 194.0.11.50
    port: 6379
  #    password: 888888
    timeout: 10000
    pool:
        # 连接池中的最大空闲连接
       max-idle: 8
        # 连接池中的最小空闲连接
       min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
       max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
       max-wait: -1
