server:
  port: 8085
spring:
  profiles:
    active: pro
  aop:
    auto: true
    proxy-target-class: true
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
      suffix: .html
      encoding: UTF-8
      servlet:
        content-type: text/html
      prefix: classpath:/templates/


mybatis:
  configuration:
    mapUnderscoreToCamelCase: false
  type-aliases-package: com.example.springbootTest.model
  mapper-locations: classpath*:mapping/*.xml

