server:
  port: 8085
spring:
  profiles:
    active: pro
  aop:
    auto: true
    proxy-target-class: true

mybatis:
  configuration:
    mapUnderscoreToCamelCase: false
  type-aliases-package: com.example.springbootTest.model
  mapper-locations: classpath*:mapping/*.xml

