server:
  port: 8085
spring:
  profiles:
    active: pro
mybatis:
  configuration:
    mapUnderscoreToCamelCase: false
  type-aliases-package: com.example.springbootTest.model
  mapper-locations: classpath*:mapping/*.xml

logging:
  config: classpath:logback-pro.xml