server:
  port: 8010
spring:
  rabbitmq:
    host: 194.0.11.58
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 2
        max-concurrency: 100
#        prefetch: 2

