server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 888888
  activiti:
    check-process-definitions: false
    database-schema-update: true
flowable:
#关闭定时任务JOB
  async-executor-activate: false
#  db-history-used: false
#  rest-api-enabled: true

