server:
  port: 8011
spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lss0555?serverTimezone=UTC
    username: root
    password: 888888
  redis:
    host: 194.0.11.50
    port: 6379
    password: 888888
    timeout: 10000
    jedis:
      pool:
        max-idle: 8
        min-idle: 10
        max-active: 100
        max-wait: -1
mybatis:
  configuration:
    mapUnderscoreToCamelCase: false
  type-aliases-package: com.example.redis.model
  mapper-locations: classpath*:mapping/*.xml